//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSV.EFModel
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Threading.Tasks;

    public partial class GiveeEntities : DbContext
    {
        public GiveeEntities()
            : base("name=GiveeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> users { get; set; }
        public List<user> GetNonExistingUsers(DataTable userTable)
        {
            var parameter = new SqlParameter("@UserTable", SqlDbType.Structured)
            {
                TypeName = "dbo.UserTableType", // Adjust to match your table type name
                Value = userTable
            };

            var result = this.Database.SqlQuery<user>("EXEC GetNonExistingUsers @UserTable", parameter).ToList();
            return result;
        }
          public Database GetDatabase() => base.Database;
    }
}
